### ISSUE TITLE
Why Strings are Not Accepted for Date Columns

### ISSUE THREAD

**Issue by Alxander64** [mymarilyn/clickhouse-driver#217]
**Describe the bug**
When trying to insert properly formatted date strings into Date columns, the client gives an error.
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 242, in execute
    rv = self.process_insert_query(
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 471, in process_insert_query
    rv = self.send_data(sample_block, data,
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 524, in send_data
    self.connection.send_data(block)
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/connection.py", line 554, in send_data
    self.block_out.write(block)
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/streams/native.py", line 38, in write
    write_column(self.context, col_name, col_type, items,
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/columns/service.py", line 107, in write_column
    column.write_data(items, buf)
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 77, in write_data
    self._write_data(items, buf)
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 80, in _write_data
    prepared = self.prepare_items(items)
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/columns/base.py", line 69, in prepare_items
    self.before_write_items(items, nulls_map=nulls_map)
  File "/home/alex/.local/lib/python3.8/site-packages/clickhouse_driver/columns/datecolumn.py", line 33, in before_write_items
    item = date(item.year, item.month, item.day)
AttributeError: 'str' object has no attribute 'year'
```

**To Reproduce**
Try inserting strings into columns of type Date.
```
CREATE TABLE testing (
    date Date,
    msg String
) ENGINE MergeTree
ORDER BY date
PARTITION BY date
```
```
from clickhouse_driver import Client
client = Client('localhost')
client.execute('INSERT INTO testing (date, msg) VALUES', [{'date': '2021-05-13', 'msg': 'hello'}])
```

**Expected behavior**
I see in the documentation for type Date the only supported values for inserting are `date` and `datetime` objects. I'm not sure if this also supports integer unix timestamps but just isn't mentioned for whatever reason.

I don't see why the client shouldn't also accept strings and attempt to parse them into `date` objects for the user. It would just be more convenient. The reason why I'm hoping the client library can help with this is because I run some applications which consume streaming data and ingest batches into ClickHouse, preferrably without having to make any transformations to the original data.

Also in the official documentation for Date [here](https://clickhouse.tech/docs/en/sql-reference/data-types/date/) is shows date formatted strings as I have shown above bring inserted via the command line client, and so I naturally assumed the Python client would accept the same.

**Versions**
- clickhouse-driver 0.2.0
- Python 3.8

**Comment by pranay01** [comment]
Any updates on this? I am facing the same issue

**Comment by xzkostyan** [comment]
Hi.

Sorry for not getting back to you sooner.

> I don't see why the client shouldn't also accept strings and attempt to parse them into date objects for the user.

There are lots of date formats. What format should we use? The particular one or multiple formats and why?

> It would just be more convenient. The reason why I'm hoping the client library can help with this is because I run some applications which consume streaming data and ingest batches into ClickHouse, preferrably without having to make any transformations to the original data.

Yes, it would be more convenient at first. But, it's really hard to make arbitrary external stream happy with proper parsing. That's why parsing is delegated to client's code. It's not so hard to implement custom date parser. 

> Also in the official documentation for Date here is shows date formatted strings as I have shown above bring inserted via the command line client, and so I naturally assumed the Python client would accept the same.

`clickhouse-client` is CLI too that **parses query** and sends it to `clickhouse-server`. In `clickhouse-driver` any parsing is eliminated for [performance](https://clickhouse-driver.readthedocs.io/en/latest/quickstart.html?highlight=using#inserting-data). Any conditional parsing is significantly slows down INSERTs, since we need to check each element where it parsed or not. This is not required in the most cases.

If you need to parse original data (strings) you can always do it [with generator](https://clickhouse-driver.readthedocs.io/en/latest/misc.html#inserting-data-from-csv-file).

I hope it's a little bit clear now why there is no parsing in `clickhouse-driver`.
