### ISSUE TITLE
How to enable multi-statement execution?

### ISSUE THREAD

**Issue by kartikeyporwal** [mymarilyn/clickhouse-driver#427]
In a `ReplicatedReplacingMergeTree` table, I am trying to make `ALTER ... UPDATE` command a synchronous operation using command like

```
SET mutations_sync = 2;
ALTER TABLE my_table_name
ON CLUSTER '{cluster}'
UPDATE my_column_name = 0
WHERE my_column_name IS NULL;
```

This particular command works in `dbeaver` when I collectively run this. But when I added it in `clickhouse_driver_client.execute()` statement, I am getting error like `DB::Exception: Syntax error (Multi-statements are not allowed): failed at position 36 (end of query) (line 2, col 35): ;`

How can I enable multi statement execution in clickhouse driver?

**Comment by xzkostyan** [comment]
Hi.

Multi-statements are not supported. To support it we need to parse sequence of SQL queries with AST that constantly changes due to new features in ClickHouse. I don't want to accept this challenge. That's why multi-statements are not supported.

I guess you want this: `client.execute(..., settings={'mutations_sync': 2})`.

This will execute query with this option set.
