### ISSUE TITLE
Support LowCardinality data type

### ISSUE THREAD

**Issue by 5cmpersec** [mymarilyn/clickhouse-driver#80]
Please support `LowCardinality` data type.

```
clickhouse_driver.errors.UnknownTypeError: Code: 50. Unknown type LowCardinality(String)
```

**Comment by wawaka** [comment]
version 0.0.16 is the last version to work fine with LowCardinality types

**Comment by xzkostyan** [comment]
LowCardinality type was broken in 0.0.17 with native protocol [version bump to 54406](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Core/Defines.h#L49) for server logs displaying.

But [since 54405](https://github.com/yandex/ClickHouse/blob/master/dbms/src/Core/Defines.h#L57) protocol version client *must* support LowCardinality type. Before this version ClickHouse server was transforming `LowCardinality(T)` into `T` on the fly.

LowCardinality support is in master now. You can install it [directly from github](https://clickhouse-driver.readthedocs.io/en/latest/installation.html#installation-from-github).

Any feedback is appreciated.
